const $=id=>document.getElementById(id);
const maps=(q,type="google")=>type==="naver"?`https://map.naver.com/p/search/${encodeURIComponent(q)}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const clone=v=>JSON.parse(JSON.stringify(v));
function loadState(){const saved=JSON.parse(localStorage.getItem("tripStateV5")||"null");const old=JSON.parse(localStorage.getItem("tripStateV4")||"null");const source=saved||old||{};return{budgetLimit:Number(source.budgetLimit)||defaultState.budgetLimit,rate:Number(source.rate)||defaultState.rate,rateDate:source.rateDate||"",expenses:Array.isArray(source.expenses)?source.expenses.map(e=>({...e,scope:e.scope||"total"})):clone(defaultExpenses),packing:Array.isArray(source.packing)?source.packing:clone(defaultPacking),momMode:Boolean(source.momMode)}}
let state=loadState();const save=()=>localStorage.setItem("tripStateV5",JSON.stringify(state));let selectedDay=0,selectedDistrict="弘大",selectedCat="全部",selectedPackingType="隨身物品";
function showPage(page){document.querySelectorAll(".page").forEach(el=>el.classList.toggle("active",el.id===page));document.querySelectorAll(".nav-btn").forEach(el=>el.classList.toggle("active",el.dataset.page===page));window.scrollTo({top:0,behavior:"smooth"});if(page==="budget")renderBudget();if(page==="prep")renderPacking()}
document.querySelectorAll(".nav-btn").forEach(btn=>btn.addEventListener("click",()=>showPage(btn.dataset.page)));
function setCountdown(){const departure=new Date("2026-07-30T01:25:00+08:00");const days=Math.ceil((departure-new Date())/86400000);$("countdown").textContent=days>0?`倒數 ${days} 天`:days===0?"今天出發":"旅程進行中"}
function renderDays(){$("dayChips").innerHTML=itinerary.map((d,i)=>`<button type="button" class="chip ${i===selectedDay?"active":""}" data-day="${i}">${d.date} ${d.title.split("・")[0]}</button>`).join("");$("dayChips").querySelectorAll("[data-day]").forEach(btn=>btn.addEventListener("click",()=>{selectedDay=Number(btn.dataset.day);renderDays();renderTimeline()}))}
function tagClass(status){if(status==="釜山 Pass")return"pass";if(status&&status!=="待預約")return"booked";return""}
function renderTimeline(){const day=itinerary[selectedDay];const events=day.events.map(e=>{const naver=e.naver||(e.mapQuery?maps(e.mapQuery,"naver"):"");const google=e.mapQuery?maps(e.mapQuery):"";return`<article class="event"><div class="time">${e.time}</div><h3>${e.title}</h3>${e.detail?`<div class="transport">${e.detail}</div>`:""}${e.exit?`<div class="exit">🚇 ${e.exit}</div>`:""}${e.status?`<div class="tags"><span class="tag ${tagClass(e.status)}">${e.status}</span></div>`:""}${(naver||google)?`<div class="actions">${naver?`<a class="btn soft" target="_blank" rel="noopener" href="${naver}">NAVER</a>`:""}${google?`<a class="btn white" target="_blank" rel="noopener" href="${google}">Google Maps</a>`:""}</div>`:""}</article>`}).join("");$("timeline").innerHTML=`<h3 class="serif" style="margin:0 0 21px">${day.date}｜${day.title}</h3>${events}`}
const districts=()=>Object.keys(places);const categories=()=>["全部",...new Set(places[selectedDistrict].map(p=>p.category))];
function renderExplore(){$("districtTabs").innerHTML=districts().map(d=>`<button type="button" class="chip ${d===selectedDistrict?"active":""}" data-district="${d}">${d}</button>`).join("");$("districtTabs").querySelectorAll("[data-district]").forEach(btn=>btn.addEventListener("click",()=>{selectedDistrict=btn.dataset.district;selectedCat="全部";renderExplore()}));$("categoryTabs").innerHTML=categories().map(c=>`<button type="button" class="chip ${c===selectedCat?"active":""}" data-cat="${c}">${c}</button>`).join("");$("categoryTabs").querySelectorAll("[data-cat]").forEach(btn=>btn.addEventListener("click",()=>{selectedCat=btn.dataset.cat;renderExplore()}));const list=places[selectedDistrict].filter(p=>selectedCat==="全部"||p.category===selectedCat);$("placeGrid").innerHTML=list.map(p=>{const query=p.address||`${p.name} ${selectedDistrict}`;const naver=p.naver||maps(query,"naver");return`<article class="place-card"><div class="place-head"><h3>${p.name}</h3><span class="place-category">${p.category}</span></div><p>${p.description}</p>${p.address?`<p class="place-address">${p.address}</p>`:""}<div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="${naver}">NAVER</a><a class="btn white" target="_blank" rel="noopener" href="${maps(query)}">Google Maps</a></div></article>`}).join("")||`<div class="card">這個分類目前沒有地點。</div>`}
function money(n,currency="TWD"){return new Intl.NumberFormat("zh-TW",{style:"currency",currency,maximumFractionDigits:0}).format(n)}
function toTwd(e){const amount=Number(e.amount)||0;const twd=e.currency==="KRW"?amount*state.rate:amount;return e.scope==="person"?twd:twd/2}
function renderBudget(){$("budgetLimit").value=state.budgetLimit;const total=state.expenses.reduce((s,e)=>s+toTwd(e),0);$("budgetTotal").textContent=money(total);$("budgetBar").style.width=`${Math.min(100,total/state.budgetLimit*100)||0}%`;const sums={};state.expenses.forEach(e=>sums[e.category]=(sums[e.category]||0)+toTwd(e));$("categorySummary").innerHTML=Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([cat,val])=>`<div class="category-box"><span>${cat}</span><b>${money(val)}／人</b></div>`).join("");$("expenseList").innerHTML=state.expenses.map(e=>`<div class="expense-row"><div class="grow"><b>${e.name}</b><div class="sub">${e.category}・${e.status}・${e.scope==="person"?"每人價格":"兩人總價"}</div></div><div><b>${money(Number(e.amount),e.currency)}</b><div class="sub">≈ ${money(toTwd(e))}／人</div></div><div class="row-actions"><button class="icon-btn" type="button" onclick="editExpense('${e.id}')">✎</button><button class="icon-btn danger" type="button" onclick="deleteExpense('${e.id}')">⌫</button></div></div>`).join("");updateRateUI()}
$("budgetLimit").addEventListener("change",e=>{state.budgetLimit=Math.max(0,Number(e.target.value)||0);save();renderBudget()});
function openExpenseModal(){$("expenseModalTitle").textContent="新增支出";$("expenseForm").reset();$("expenseId").value="";$("expenseScope").value="total";$("expenseModal").classList.add("open")}
function editExpense(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;$("expenseModalTitle").textContent="修改支出";$("expenseId").value=e.id;$("expenseName").value=e.name;$("expenseAmount").value=e.amount;$("expenseCurrency").value=e.currency;$("expenseCategory").value=e.category;$("expenseStatus").value=e.status;$("expenseScope").value=e.scope||"total";$("expenseModal").classList.add("open")}
function deleteExpense(id){if(!confirm("確定刪除這筆支出？"))return;state.expenses=state.expenses.filter(e=>e.id!==id);save();renderBudget()}
$("expenseForm").addEventListener("submit",e=>{e.preventDefault();const id=$("expenseId").value||`expense-${Date.now()}`;const item={id,name:$("expenseName").value.trim(),amount:Number($("expenseAmount").value),currency:$("expenseCurrency").value,category:$("expenseCategory").value,status:$("expenseStatus").value,scope:$("expenseScope").value};const index=state.expenses.findIndex(x=>x.id===id);index>=0?state.expenses[index]=item:state.expenses.push(item);save();closeModal("expenseModal");renderBudget()});
async function fetchRate(){$("liveRate").textContent="讀取中…";try{const response=await fetch("https://api.frankfurter.dev/v2/rate/KRW/TWD",{cache:"no-store"});if(!response.ok)throw new Error("rate");const data=await response.json();state.rate=Number(data.rate);state.rateDate=data.date||new Date().toISOString().slice(0,10);save();renderBudget();updateConverter()}catch{$("liveRate").textContent=`目前使用備用匯率：1 KRW ≈ ${state.rate.toFixed(5)} TWD`;$("rateDate").textContent="無法連線更新"}}
function updateRateUI(){$("liveRate").textContent=`1 KRW ≈ ${state.rate.toFixed(5)} TWD`;$("rateDate").textContent=state.rateDate?`更新 ${state.rateDate}`:"尚未更新"}
function updateConverter(){const amount=Number($("fxAmount").value)||0;if($("fxDirection").value==="KRW_TWD")$("fxResult").textContent=`${money(amount,"KRW")} ≈ ${money(amount*state.rate,"TWD")}`;else $("fxResult").textContent=`${money(amount,"TWD")} ≈ ${money(amount/state.rate,"KRW")}`}
$("refreshRate").addEventListener("click",fetchRate);$("fxAmount").addEventListener("input",updateConverter);$("fxDirection").addEventListener("change",updateConverter);
const packingTypes=()=>["隨身物品","托運行李"];
function renderPacking(){$("packingTabs").innerHTML=packingTypes().map(t=>`<button type="button" class="chip ${t===selectedPackingType?"active":""}" data-pack="${t}">${t}</button>`).join("");$("packingTabs").querySelectorAll("[data-pack]").forEach(btn=>btn.addEventListener("click",()=>{selectedPackingType=btn.dataset.pack;renderPacking()}));const list=state.packing.filter(i=>i.type===selectedPackingType);const groups={};list.forEach(i=>(groups[i.category||"其他"]||=[]).push(i));$("packingList").innerHTML=Object.entries(groups).map(([cat,items])=>`<div class="group-title">${cat}</div>${items.map(i=>`<div class="check-row ${i.done?"done":""}"><input type="checkbox" ${i.done?"checked":""} onchange="togglePacking('${i.id}')"><div class="grow"><b>${i.name}</b></div><div class="row-actions"><button class="icon-btn" type="button" onclick="editPacking('${i.id}')">✎</button><button class="icon-btn danger" type="button" onclick="deletePacking('${i.id}')">⌫</button></div></div>`).join("")}`).join("");const done=state.packing.filter(i=>i.done).length,total=state.packing.length;$("packingProgress").textContent=`${done}/${total}`;$("packingBar").style.width=`${total?done/total*100:0}%`}
function togglePacking(id){const item=state.packing.find(i=>i.id===id);if(item){item.done=!item.done;save();renderPacking()}}
function openPackingModal(){$("packingModalTitle").textContent="新增行李項目";$("packingForm").reset();$("packingId").value="";$("packingTypeInput").value=selectedPackingType;$("packingModal").classList.add("open")}
function editPacking(id){const p=state.packing.find(i=>i.id===id);if(!p)return;$("packingModalTitle").textContent="修改行李項目";$("packingId").value=p.id;$("packingName").value=p.name;$("packingTypeInput").value=p.type;$("packingCategory").value=p.category;$("packingModal").classList.add("open")}
function deletePacking(id){if(!confirm("確定刪除這個項目？"))return;state.packing=state.packing.filter(i=>i.id!==id);save();renderPacking()}
$("packingForm").addEventListener("submit",e=>{e.preventDefault();const id=$("packingId").value||`packing-${Date.now()}`;const old=state.packing.find(i=>i.id===id);const item={id,type:$("packingTypeInput").value,category:$("packingCategory").value.trim()||"其他",name:$("packingName").value.trim(),done:old?.done||false};const index=state.packing.findIndex(i=>i.id===id);index>=0?state.packing[index]=item:state.packing.push(item);save();selectedPackingType=item.type;closeModal("packingModal");renderPacking()});
function renderPhrases(){const groups={};phrases.forEach(p=>(groups[p.category]||=[]).push(p));$("phraseList").innerHTML=Object.entries(groups).map(([cat,items])=>`<div class="phrase-category">${cat}</div>${items.map(p=>`<div class="phrase-row"><div class="grow"><div class="phrase-korean">${p.ko}</div><div class="sub">${p.zh}</div></div><button class="icon-btn" type="button" onclick='speak(${JSON.stringify(p.ko)},"ko-KR")'>🔊</button></div>`).join("")}`).join("")}
function speak(text,lang="ko-KR"){if(!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.82;speechSynthesis.speak(u)}
async function translateText(){const text=$("translationInput").value.trim();if(!text){$("translationOutput").textContent="請先輸入內容。";return}const[source,target]=$("translationDirection").value.split("|");$("translationOutput").textContent="翻譯中…";try{const url=`https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${encodeURIComponent(source+"|"+target)}`;const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error("translation");const data=await response.json();const translated=data?.responseData?.translatedText;if(!translated)throw new Error("translation");$("translationOutput").textContent=translated}catch{$("translationOutput").textContent="目前無法取得翻譯，請稍後再試。"}}
$("translateBtn").addEventListener("click",translateText);$("speakTranslation").addEventListener("click",()=>{const target=$("translationDirection").value.split("|")[1];speak($("translationOutput").textContent,target==="ko"?"ko-KR":"zh-TW")});$("copyTranslation").addEventListener("click",async()=>{await navigator.clipboard.writeText($("translationOutput").textContent);$("copyTranslation").textContent="已複製";setTimeout(()=>$("copyTranslation").textContent="複製",1200)});
function closeModal(id){$(id).classList.remove("open")}document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("open")}));
$("momToggle").addEventListener("click",()=>{state.momMode=!state.momMode;save();applyMomMode()});function applyMomMode(){document.body.classList.toggle("mom",state.momMode);$("momToggle").textContent=state.momMode?"一般模式":"👩 媽媽模式"}
setCountdown();renderDays();renderTimeline();renderExplore();renderBudget();renderPacking();renderPhrases();applyMomMode();updateConverter();fetchRate();